### PR TITLE
fix: marshaling for useAppOauthScopedToken provider configuration

### LINKED ISSUE #569: oAuth App Authentication Support is missing
### Describe what happened

I'm trying to set up PagerDuty using the provider and trying to authenticate using oAuth app clientID + secret + subdomain. Unfortunately when I try doing so I get the following error every time:
```
    error: Cannot obtain plugin client:
    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.
```

If I switch to token-based v2 auth everything works as expected.

### Sample program

Pulumi.yaml:
```
name: service-trains
runtime: yaml
description: PagerDuty bug
resources:
  pdProvider:
    type: pulumi:providers:pagerduty
    properties:
#      token: ${pagerduty:token}
      useAppOauthScopedToken:
        pdClientId: ${pagerduty:clientId}
        pdClientSecret: ${pagerduty:clientSecret}
        pdSubdomain: ${pagerduty:subdomain}
    options:
      version: 4.13.2
  devsUser:
    type: pagerduty:User
    properties:
      email: some-email@example.com
      name: Dev Team
      description: Development team
      jobTitle: Devs
      role: limited_user
    options:
      provider: ${pdProvider}
```

Pulumi.pagerduty.yaml:
```
config:
  pagerduty:clientId:
    secure: some-secret
  pagerduty:clientSecret:
    secure: some-secret
  pagerduty:subdomain: some-sub-domain
  pagerduty:token:
    secure: some-secret
  pulumi:disable-default-providers:
    - "*"
```

### Log output

Diagnostics:
  pagerduty:index:User (devsUser):
    error: Cannot obtain plugin client:
    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.

### Affected Resource(s)

pagerduty:User

### Output of `pulumi about`

pulumi about
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME  VERSION
language  yaml  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in yaml

Current Stack: CURRENT_STACK

TYPE                          URN
<STACKS>

Found no pending operations associated with travelshift/pagerduty

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xSAVIKx
User           xSAVIKx
Organizations  <ORGS>
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by gunzy83**
### Summary

This PR fixes https://github.com/pulumi/pulumi-pagerduty/issues/569. It seems that the `useAppOauthScopedToken` provider configuration option is being passed as nil to the underlying Terraform provider variable `use_app_oauth_scoped_token`. I think this was likely due to a change between 4.8.1 and 4.9.0 that switches the Pulumi provider to be a muxed provider (`pftfbridge.MainWithMuxer`), the upstream provider is also muxed and the bridge is a bit conservative and sends an Object while the SDKv2 part of the provider is still looking for a list of length 1.

### Changes

* `provider/resources.go`: Explicitly mapped the `use_app_oauth_scoped_token` configuration field.
  * Defined explicit Fields mapping for `pd_client_id`, `pd_client_secret`, and `pd_subdomain` to ensure consistent camelCase to snake_case translation.
* Added `MaxItemsOne: tfbridge.True()` to ensure the Pulumi object is correctly wrapped into a single-element list before being passed to the Terraform provider.

There were no changes to `bridge-metadata.json` when `make tfgen` was run.

### Testing

Tested locally by building the provider and using PULUMI_DEBUG_PROVIDERS with a NodeJS consumer project after running `npm install $PROJECT_DIR/sdk/nodejs` that was previously using v4.8.1.

Upgrading to 4.9.0 and above would cause the following error (also in the issue above):

```
    error: Cannot obtain plugin client:
    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.
```

I was able to deploy a new set of resources for a debug service we usually do not deploy and then remove them without issue.

### CODE REVIEW

File: provider/resources.go [hunk 1]
```diff
@@ -93,6 +93,16 @@ func Provider() tfbridge.ProviderInfo {
 					Value: false,
 				},
 			},
+			"use_app_oauth_scoped_token": {
+				MaxItemsOne: tfbridge.True(),
+				Elem: &tfbridge.SchemaInfo{
+					Fields: map[string]*tfbridge.SchemaInfo{
```
Comment (guineveresaenger) [inline provider/resources.go]: I believe these are redundant. They're [already properly translated in the schema](urlhttps://github.com/pulumi/pulumi-pagerduty/blob/master/provider/cmd/pulumi-resource-pagerduty/schema.json#L76). 

Please remove them and then we can merge!

**Review by guineveresaenger — CHANGES_REQUESTED** [review]
Thank you so much for this fix. It's an upstream bug - upstream is [missing a size validator on the migrated block](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/master/pagerdutyplugin/provider.go#L30) but we can fortunately address this here with a knob as well.

Please remove the extra fields, and then we can merge!

File: provider/resources.go (hunk 1 above)
Comment (gunzy83) [reply provider/resources.go]: Thanks. I removed the extra fields and re-ran my local testing and you are indeed correct, the field are redundant and it was just the size validator that needed to be dealt with on the Pulumi side.

**Review by guineveresaenger — APPROVED** [review]
