### PR TITLE
DocsEdits for pagerduty.Service

### LINKED ISSUE #477: Incorrect function argument type for the Service resource incidentUrgencyRule arg
### What happened?

I was trying to create a new PagerDuty service with an incidentUrgencyRule, and noticed that the "type" argument specified in the code documentation could not be accepted.

### Example

export const srv = new pagerduty.Service(
  'test-service-gkm',
  {
    name: `${serviceName}-gkm`,
    description: `PagerDuty service for ${serviceName}`,
    escalationPolicy: 'SOMEID',
    alertGroupingParameters: {
      type: 'intelligent',
    },
    autoPauseNotificationsParameters: {
      enabled: true,
      timeout: 300,
    },
    autoResolveTimeout: 'null',
    incidentUrgencyRule: {
      type: 'intelligent',
      duringSupportHours: {
        type: 'intelligent',
        urgency: 'severity_based',
      },
      outsideSupportHours: {
        type: 'intelligent',
        urgency: 'severity_based',
      },
      urgency: 'severity_based',
    },
  },
  { provider: providerPg },
);

### Output of `pulumi about`

`CLI          
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME       VERSION
aws        6.13.3
awsx       2.3.0
docker     4.5.0
docker     3.6.1
dynatrace  0.1.0
nodejs     unknown
pagerduty  4.11.4

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in nodejs: executable='/.nvm/versions/node/v18.18.2/bin/node' version='v18.18.2'

Current Stack: ORG/simple-pulumi-project/dev

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:dev::simple-pulumi-project::pulumi:pulumi:Stack::simple-pulumi-project-dev
pulumi:providers:pagerduty       urn:pulumi:dev::simple-pulumi-project::pulumi:providers:pagerduty::pagerduty
pagerduty:index/service:Service  urn:pulumi:dev::simple-pulumi-project::pagerduty:index/service:Service::test-service-gkm

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/gkm
User           USER
Organizations  ORG
Token type     personal

Dependencies:
NAME                       VERSION
@pulumi/awsx               2.3.0
@pulumi/pagerduty          4.11.4
@pulumi/pulumi             3.97.0
@types/node                18.19.3
prettier                   3.2.5
@lbrlabs/pulumi-dynatrace  0.1.0
@pulumi/aws                6.13.3

Pulumi locates its logs in /var/folders/d2/bcyz_mjx4n36884cl5s2vdnm0000gq/T/ by default`

### Additional context

The error message

`Diagnostics:
  pulumi:pulumi:Stack (simple-pulumi-project-dev):
    error: update failed

  pagerduty:index:Service (test-service-gkm):
    error: 1 error occurred:
    	* POST API call to https://api.pagerduty.com/services failed 400 Bad Request. Code: 2001, Errors: [Type must be in constant or use_support_hours.], Message: Invalid Input Provided
`

The docs link

https://www.pulumi.com/registry/packages/pagerduty/api-docs/service/#serviceincidenturgencyrule

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
Due to [somewhat nonstandard](https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/service) block descriptions, we were omitting some fields on pagerduty.Service doc.

This pull request adds a docEdit rule that strips all of the extraneous text from the nested block description and rewrites it to reflect the nested blocks format the bridge expects.

This fixes field descriptions for `ServiceSupportHours`, `ServiceScheduledAction`, and `ServiceIncidentUrgencyRule` nested blocks.

Note that this PR is also build off of latest bridge rather than a release, to incorporate the much larger markdown parsing changes made in https://github.com/pulumi/pulumi-terraform-bridge/pull/2006.

Further note that this PR drops the additional information contained in the irregular block descriptions. This is the current status quo for all Pulumi providers. We additionally do not currently render extra information in the nested properties sections. 

Closes #477.

### CODE REVIEW

File: provider/resources.go [hunk 1]
```diff
@@ -219,5 +221,32 @@ func Provider() tfbridge.ProviderInfo {
...
+	return append(defaults, tfbridge.DocsEdit{
+		Path: "service.html.markdown",
+		Edit: func(_ string, content []byte) ([]byte, error) {
+
+			content = bytes.Replace(content,
+				[]byte("You may specify one optional `incident_urgency_rule` block configuring what urgencies to "+
+					"use.\nYour PagerDuty account must have the `urgencies` ability to assign an incident urgency "+
+					"rule.\nThe block contains the following arguments:"),
+				[]byte("The `incident_urgency_rule` block contains the following arguments:"),
+				1)
```
Comment (iwahbe) [inline provider/resources.go:234]: Why not replace all here?

**Review by iwahbe — COMMENTED** [review]
It would be much easer to see the effects here if you regenerated the SDKs.

**Review by VenelinMartinov — COMMENTED** [review]
+1 for regenerating the SDK - the schema is very hard to diff as the lines are endless.

Also let's wait for the bridge release if we need the changes there or merge the docsEdit rule without the pin.

**Comment by VenelinMartinov** [comment]
```
git checkout master
git merge guin/fix-service-docs
go run ../pus
> $schema Diff
No schema changes between HEAD and current version
```

Am I misunderstanding the tool?

File: provider/resources.go (hunk 1 above)
Comment (guineveresaenger) [reply provider/resources.go:234]: I find it unintuitive to use ReplaceAll when there's only one incidence of the text. 🤷‍♀️

**Comment by guineveresaenger** [comment]
Apologies - I did forget to generate the SDKs here.
I agree with @VenelinMartinov that we want to wait for the bridge release.
